### ISSUE TITLE
Feature Request: Disable Modules

### ISSUE THREAD

**Issue by mikezielonka** [jdevalk/comment-hacks#108]
Long time fan of comment hacks!  My favorite feature is clean comment notification emails. 😃

I'd love a simple UI or set of filters that I could use to disable the unused modules of the plugin.

For example, my customers nor I will use the email all commenters feature and the mail icon slightly bugs me as a minimalist :)

**Comment by jdevalk** [comment]
Good suggestion! Fixed in 1.9.3 :)

**Comment by mikezielonka** [comment]
> Good suggestion! Fixed in 1.9.3 :)

Thanks @jdevalk!  Happy New Year!
