### ISSUE TITLE
Dropdown for Comment notification recipients not saving changes

### ISSUE THREAD

**Issue by CircuitStarG** [jdevalk/comment-hacks#111]
* [x] I've read and understood the [contribution guidelines](https://github.com/jdevalk/pdf-xml-sitemap/blob/main/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened
Hello. Been using the plugin for a few years. Inside the posts, I've been using the dropdown to change the comment notifications from "Post Author" to another use (me), and we just realized now that it hasn't been working. After I select my user name in the dropdown and click update, if you go back into the post it still says "post author".

#### Step-by-step reproduction instructions
1. Edit a post and go to Comment notification recipients dropdown in the right sidebar
2. change the recipient from 'post author' to another user
3. Save/update post

#### Expected results
1. when edit post later, the 'new' user to receive comments is indicated in the dropdown

#### Actual results
1. still says 'post author'

### Screenshots, screen recording, code snippet
If possible, please provide a screenshot, a screen recording or a code snippet which demonstrates the bug.

#### Used versions
* Device you are using: PC
* Operating system: Windows 11
* PHP version: 8.1.26
* WordPress version: Version 6.3.2
* WordPress Theme: Genesis 3.3.1 and Feast Plugin Version 10.0.6
* Plugin version: Version 1.9.2
* Relevant plugins in case of a bug:

**Comment by jdevalk** [comment]
Annoying :) fixed in 1.9.3
