### ISSUE TITLE
Customization of comment_notes_before

### ISSUE THREAD

**Issue by Myddna** [jdevalk/comment-hacks#26]
Hi!

Do yo plan on making the text in comment_notes_before ('You have to agree to the comment policy.') customizable?

[Link to search in this repository](https://github.com/Yoast/comment-hacks/search?utf8=%E2%9C%93&q=comment_notes_before&type=)

Thanks :)

**Comment by jdevalk** [comment]
Hmm that's a leftover of something I wanted to build. Now deploying something much better :)

**Comment by jdevalk** [comment]
See https://github.com/jdevalk/comment-hacks/pull/106
