### ISSUE TITLE
SyntaxError: JSON Parse error: Unexpected identifier "Error" 

### ISSUE THREAD

**Issue by claymade** [jdevalk/comment-hacks#34]
Yoast Comment Hacks is making an error when anyone is trying to comment. SyntaxError: JSON Parse error: Unexpected identifier "Error" It seems to be in conflict with WPDiscuz. Version 5.3.1. My site effected is GetAlongWithGod.com. I have turned off the Yoast Comment Hacks for now to allow comments. Do you have any recommendations?

**Comment by jdevalk** [comment]
It's... weird but this plugin never parses JSON, so I don't think this bug is on our end?
